import moment from 'moment';

export default [
  {
    id: 'A0001',
    address: {
      country: 'USA',
      state: 'West Virginia',
      city: 'Parkersburg',
      street: '2849 Fulton Street'
    },
    avatarUrl: '/static/images/avatars/avatar_3.png',
    createdAt: 1555016400000,
    email: 'ekaterina.tankova@devias.io',
    name: 'Nguyễn Văn Thành',
    dentistry: 'Nha Khoa Gia Định',
    dentist: 'BS Kim Đoàn Thái',
    phone: '304-428-3097',
    price: '500.000',
    type: 'Đơn mới',
    receiveDate: moment().format('DD-MM-YYYY'),
    releaseDate: moment().format('DD-MM-YYYY'),
    receiveTime: '08:00',
    releaseTime: '09:00',
    description: '7 - FMC',
    count: 1,
    color: 'Xanh',
    note: 'Thời gian hoàn thành lâu hơn dự kiến',
    finishDate: moment().format('DD-MM-YYYY'),
    finishTime: '17:30',
    department: 'ABC',
    employee: 'Trần Văn Trung',
    wage: '150.000',
  },
  {
    id: 'A0002',
    address: {
      country: 'USA',
      state: 'Bristow',
      city: 'Iowa',
      street: '1865  Pleasant Hill Road'
    },
    avatarUrl: '/static/images/avatars/avatar_4.png',
    createdAt: 1555016400000,
    email: 'cao.yu@devias.io',
    name: 'Trần Văn Trung',
    dentistry: 'Nha Khoa An Bình',
    dentist: 'BS Thi Thiên',
    phone: '712-351-5711',
    price: '650.000',
    receiveDate: moment().format('DD-MM-YYYY'),
    releaseDate: moment().format('DD-MM-YYYY'),
    type: 'Đơn mới',
    receiveTime: '08:00',
    releaseTime: '09:00',
    description: '7 - FMC',
    count: 1,
    color: 'Xanh',
    note: 'Thời gian hoàn thành lâu hơn dự kiến',
    finishDate: moment().format('DD-MM-YYYY'),
    finishTime: '17:30',
    department: 'ABC',
    employee: 'Trần Văn Trung',
    wage: '150.000',
  },
  {
    id: 'A0003',
    address: {
      country: 'USA',
      state: 'Georgia',
      city: 'Atlanta',
      street: '4894  Lakeland Park Drive'
    },
    avatarUrl: '/static/images/avatars/avatar_2.png',
    createdAt: 1555016400000,
    email: 'alexa.richardson@devias.io',
    name: 'Nguyễn Hải Châu',
    dentistry: 'Nha Khoa Thủ Đức',
    dentist: 'BS Trương Hiền',
    phone: '770-635-2682',
    price: '500.000',
    receiveDate: moment().format('DD-MM-YYYY'),
    releaseDate: moment().format('DD-MM-YYYY'),
    type: 'Đơn mới',
    receiveTime: '08:00',
    releaseTime: '09:00',
    description: '7 - FMC',
    count: 1,
    color: 'Xanh',
    note: 'Thời gian hoàn thành lâu hơn dự kiến',
    finishDate: moment().format('DD-MM-YYYY'),
    finishTime: '17:30',
    department: 'ABC',
    employee: 'Trần Văn Trung',
    wage: '150.000',
  },
  {
    id: 'A0004',
    address: {
      country: 'USA',
      state: 'Ohio',
      city: 'Dover',
      street: '4158  Hedge Street'
    },
    avatarUrl: '/static/images/avatars/avatar_5.png',
    createdAt: 1554930000000,
    email: 'anje.keizer@devias.io',
    name: 'Võ Huy Liệu',
    dentistry: 'Nha Khoa Nguyễn Trãi',
    dentist: 'BS Bửu Mộng Trúc',
    phone: '908-691-3242',
    price: '960.000',
    receiveDate: moment().format('DD-MM-YYYY'),
    releaseDate: moment().format('DD-MM-YYYY'),
    type: 'Đơn mới',
    receiveTime: '08:00',
    releaseTime: '09:00',
    description: '7 - FMC',
    count: 1,
    color: 'Xanh',
    note: 'Thời gian hoàn thành lâu hơn dự kiến',
    finishDate: moment().format('DD-MM-YYYY'),
    finishTime: '17:30',
    department: 'ABC',
    employee: 'Trần Văn Trung',
    wage: '150.000',
  },
  {
    id: 'A0005',
    address: {
      country: 'USA',
      state: 'Texas',
      city: 'Dallas',
      street: '75247'
    },
    avatarUrl: '/static/images/avatars/avatar_6.png',
    createdAt: 1554757200000,
    email: 'clarke.gillebert@devias.io',
    name: 'Vũ Kiến Trung',
    dentistry: 'Nha Khoa Nhân Ái',
    dentist: 'BS An Tấn',
    phone: '972-333-4106',
    price: '500.000',
    receiveDate: moment().format('DD-MM-YYYY'),
    releaseDate: moment().format('DD-MM-YYYY'),
    type: 'Đơn mới',
    receiveTime: '08:00',
    releaseTime: '09:00',
    description: '7 - FMC',
    count: 1,
    color: 'Xanh',
    note: 'Thời gian hoàn thành lâu hơn dự kiến',
    finishDate: moment().format('DD-MM-YYYY'),
    finishTime: '17:30',
    department: 'ABC',
    employee: 'Trần Văn Trung',
    wage: '150.000',
  },
  {
    id: 'A0006',
    address: {
      country: 'USA',
      state: 'California',
      city: 'Bakerfield',
      street: '317 Angus Road'
    },
    avatarUrl: '/static/images/avatars/avatar_1.png',
    createdAt: 1554670800000,
    email: 'adam.denisov@devias.io',
    name: 'Adam Denisov',
    dentistry: 'Nha Khoa Nguyễn Tri Phương',
    dentist: 'BS Kim Đoàn Thái',
    phone: '858-602-3409',
    price: '800.000',
    receiveDate: moment().format('DD-MM-YYYY'),
    releaseDate: moment().format('DD-MM-YYYY'),
    type: 'Đơn mới',
    receiveTime: '08:00',
    releaseTime: '09:00',
    description: '7 - FMC',
    count: 1,
    color: 'Xanh',
    note: 'Thời gian hoàn thành lâu hơn dự kiến',
    finishDate: moment().format('DD-MM-YYYY'),
    finishTime: '17:30',
    department: 'ABC',
    employee: 'Trần Văn Trung',
    wage: '150.000',
  },
  {
    id: 'A0007',
    address: {
      country: 'USA',
      state: 'California',
      city: 'Redondo Beach',
      street: '2188  Armbrester Drive'
    },
    avatarUrl: '/static/images/avatars/avatar_7.png',
    createdAt: 1554325200000,
    email: 'ava.gregoraci@devias.io',
    name: 'Ava Gregoraci',
    dentistry: 'Nha Khoa Sài Gòn',
    dentist: 'BS Từ Hào',
    phone: '415-907-2647',
    price: '470.000',
    receiveDate: moment().format('DD-MM-YYYY'),
    releaseDate: moment().format('DD-MM-YYYY'),
    type: 'Đơn mới',
    receiveTime: '08:00',
    releaseTime: '09:00',
    description: '7 - FMC',
    count: 1,
    color: 'Xanh',
    note: 'Thời gian hoàn thành lâu hơn dự kiến',
    finishDate: moment().format('DD-MM-YYYY'),
    finishTime: '17:30',
    department: 'ABC',
    employee: 'Trần Văn Trung',
    wage: '150.000',
  },
  {
    id: 'A0008',
    address: {
      country: 'USA',
      state: 'Nevada',
      city: 'Las Vegas',
      street: '1798  Hickory Ridge Drive'
    },
    avatarUrl: '/static/images/avatars/avatar_8.png',
    createdAt: 1523048400000,
    email: 'emilee.simchenko@devias.io',
    name: 'Emilee Simchenko',
    dentistry: 'Nha Khoa Trưng Vương',
    dentist: 'BS Ninh Mẫn',
    phone: '702-661-1654',
    price: '400.000',
    receiveDate: moment().format('DD-MM-YYYY'),
    releaseDate: moment().format('DD-MM-YYYY'),
    type: 'Đơn mới',
    receiveTime: '08:00',
    releaseTime: '09:00',
    description: '7 - FMC',
    count: 1,
    color: 'Xanh',
    note: 'Thời gian hoàn thành lâu hơn dự kiến',
    finishDate: moment().format('DD-MM-YYYY'),
    finishTime: '17:30',
    department: 'ABC',
    employee: 'Trần Văn Trung',
    wage: '150.000',
  },
  {
    id: 'A0009',
    address: {
      country: 'USA',
      state: 'Michigan',
      city: 'Detroit',
      street: '3934  Wildrose Lane'
    },
    avatarUrl: '/static/images/avatars/avatar_9.png',
    createdAt: 1554702800000,
    email: 'kwak.seong.min@devias.io',
    name: 'Kwak Seong-Min',
    dentistry: 'Nha Khoa Tân Phú',
    dentist: 'BS Khưu Chính',
    phone: '313-812-8947',
    price: '1.200.000',
    receiveDate: moment().format('DD-MM-YYYY'),
    releaseDate: moment().format('DD-MM-YYYY'),
    type: 'Đơn mới',
    receiveTime: '08:00',
    releaseTime: '09:00',
    description: '7 - FMC',
    count: 1,
    color: 'Xanh',
    note: 'Thời gian hoàn thành lâu hơn dự kiến',
    finishDate: moment().format('DD-MM-YYYY'),
    finishTime: '17:30',
    department: 'ABC',
    employee: 'Trần Văn Trung',
    wage: '150.000',
  },
  {
    id: 'A0010',
    address: {
      country: 'USA',
      state: 'Utah',
      city: 'Salt Lake City',
      street: '368 Lamberts Branch Road'
    },
    avatarUrl: '/static/images/avatars/avatar_10.png',
    createdAt: 1522702800000,
    email: 'merrile.burgett@devias.io',
    name: 'Merrile Burgett',
    dentistry: 'Nha Khoa Nhà Bè',
    dentist: 'BS Phương Thảo',
    phone: '801-301-7894',
    price: '5.000.000',
    receiveDate: moment().format('DD-MM-YYYY'),
    releaseDate: moment().format('DD-MM-YYYY'),
    type: 'Đơn mới',
    receiveTime: '08:00',
    releaseTime: '09:00',
    description: '7 - FMC',
    count: 1,
    color: 'Xanh',
    note: 'Thời gian hoàn thành lâu hơn dự kiến',
    finishDate: moment().format('DD-MM-YYYY'),
    finishTime: '17:30',
    department: 'ABC',
    employee: 'Trần Văn Trung',
    wage: '150.000',
  }
];
